accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    path('user/<str:accountName>', views.account, name='account'),
    path('user/<str:accountName>/edit', views.accountEdit, name='accountEdit'),
    path('user/<str:accountName>/editMedium', views.accountEditMedium, name='accountEditMedium'),


    path('user/<str:accountName>/organisations', views.accountOrganisations, name='accountOrganisations'),
    path('user/<str:accountName>/teams', views.accountTeams, name='accountTeams'),
    path('user/<str:accountName>/advertisements', views.accountAdvertisements, name='accountAdvertisements'),

    path('user/<str:accountName>/<str:orgID>/deleteOrganisation', views.organisationDelete, name='organisationDelete'),
    path('user/<str:accountName>/<str:orgID>/deleteOrganisation/medium', views.organisationDeleteMedium, name='organisationDeleteMedium'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation', views.organisationEdit, name='organisationEdit'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation/medium', views.organisationEditMedium, name='organisationEditMedium'),


    path('user/<str:accountName>/<str:teamID>/editTeam', views.accountTeamsEdit, name='accountTeamsEdit'),
    path('user/<str:accountName>/<str:teamID>/editTeam/medium', views.accountTeamsEditMedium, name='accountTeamsEditMedium'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam', views.accountTeamsDelete, name='accountTeamsDelete'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam/medium', views.accountTeamsDeleteMedium, name='accountTeamsDeleteMedium'),

    path('user/<str:accountName>/<str:adID>/editAd', views.accountAdEdit, name='accountAdEdit'),
    path('user/<str:accountName>/<str:adID>/editAd/medium', views.accountAdEditMedium, name='accountAdEditMedium'),
    path('user/<str:accountName>/<str:adID>/deleteAd', views.accountAdDelete, name='accountAdDelete'),
    path('user/<str:accountName>/<str:adID>/deleteAd/medium', views.accountAdDeleteMedium, name='accountAdDeleteMedium'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^organisation/', include('organisation.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url('teams/', include('teams.urls')),
    path('testing', views.testing, name='testing'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from organisation import views
from django.urls import path

app_name = 'organisation'
urlpatterns = [
    #url('', views.displayTeams, name="displayTeams"),

    path('maketeam/<str:nameOfOrg>', views.addTeam, name='addTeam'),
    path('maketeamcompetition/<str:nameOfOrg>/<str:compID>', views.addTeamComp, name='addTeamComp'),
    path('maketeamcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addTeamCompMedium, name='addTeamCompMedium'),
    path('viewteams/<str:nameOfOrg>', views.viewTeams, name='viewTeams'),
    path('maketeam/medium/<str:nameOfOrg>', views.addTeamMedium, name='addTeamMedium'),
    path('jointeam/medium/<str:nameOfOrg>', views.joiningTeamMedium, name='joiningTeamMedium'),

    path('viewCompetitions/<str:nameOfOrg>', views.viewCompetitions, name='viewCompetitions'),
    path('competitionDelete/<str:compID>', views.competitionDelete, name='competitionDelete'),
    path('competitionDelete/medium/<str:compID>', views.competitionDeleteMedium, name='competitionDeleteMedium'),
    path('competitionEdit/<str:compID>', views.editCompetition, name='editCompetition'),
    path('competitionEdit/medium/<str:compID>', views.editCompetitionMedium, name='editCompetitionMedium'),

    path('competition/teamview/<str:nameOfOrg>/<str:compID>', views.viewCompetitionTeams, name='viewCompetitionTeams'),
    path('addCompetitions/<str:nameOfOrg>', views.addCompetitions, name='addCompetitions'),
    path('addCompetitions/medium/<str:nameOfOrg>', views.addCompetitionsMedium, name='addCompetitionsMedium'),

    path('makeadvertisement/<str:nameOfOrg>', views.addAdvertisement, name='addAdvertisement'),
    path('makeadvertisementcompetition/<str:nameOfOrg>/<str:compID>', views.addAdvertisementComp, name='addAdvertisementComp'),
    path('makeadvertisementcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addAdvertisementCompMedium, name='addAdvertisementCompMedium'),
    path('viewadvertisements/<str:nameOfOrg>', views.viewAdvertisements, name='viewAdvertisements'),
    path('viewadvertisementscompetition/<str:nameOfOrg>/<str:compID>', views.viewCompetitionAdvertisements, name='viewCompetitionAdvertisements'),
    path('makeadvertisement/medium/<str:nameOfOrg>', views.addAdvertisementMedium, name='addAdvertisementMedium'),



    path('makeorganisation/medium', views.makeOrgMedium, name='makeOrgMedium'),
    url('makeorganisation/fail', views.makeOrgFail, name="makeOrgFail"),
    url('makeorganisation', views.makeOrg, name="makeOrg"),
    path('home/<str:nameOfOrg>', views.organisationHome, name='organisationHome'),




    url('makeSportMedium', views.makeSportMedium, name="makeSportMedium"),
    url('makeSport', views.makeSport, name="makeSport"),

    url('testHTML', views.testHTML, name="testHTML"),

]

teams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from teams import views
urlpatterns = [

    #url('', views.displayTeams, name="displayTeams"),
    url('joining', views.joiningTeams, name="joiningTeams"),
    url('maketeam', views.makingTeams, name="makingTeams"),
]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from accounts.models import Accounts, Advertisements
from organisation.models import Organisations
from teams.models import Teams
from sports.models import Sports
from accounts.accountFunctions import *
import datetime
from .filters import AdvertisementsOwnFilter

login_path = "/accounts/login"
def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             newAccount = Accounts(accountName = request.POST['username'], userInstance = user)  #This creates the Account model, has extended fields to the User model
             newAccount.save()
             login(request, user)
             return redirect('accounts:accountEdit',request.POST['username'] )
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

@login_required(login_url="/accounts/login")
def logout_view(request):
    #if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

@login_required(login_url=login_path)
def account(request, accountName):
    try:
        accountInstance = Accounts.objects.get(accountName = accountName)
    except:
        return render(request, 'accounts/noAccount.html')

    accountInfo = {'name':accountName,'accountID':accountInstance.id, 'accountDescription':accountInstance.description,
    'gender':accountInstance.gender, 'accountInstance':accountInstance}
    return render(request, 'accounts/account.html', accountInfo)


@login_required(login_url=login_path)
def accountEdit(request, accountName):
    #try:
    genderList = ['Male', 'Female', 'Other']
    accountInstance = Accounts.objects.get(accountName = accountName)
    accountInfo = {'name':accountName,'accountID':accountInstance.id, 'accountDescription':accountInstance.description,
    'gender':accountInstance.gender, 'accountInstance':accountInstance,'genderList':genderList}





    #except:
        #return render(request, 'accounts/noAccount.html')
    return render(request, 'accounts/edit.html', accountInfo)

@login_required(login_url=login_path)
def accountEditMedium(request, accountName):
    if request.user.username == accountName:
    #this method is for when you are on the edit page, and this updates the database

        if request.method == 'POST':

             changingAccount = Accounts.objects.get(accountName = accountName)

             changingAccount.first_name = request.POST['First_Name']
             changingAccount.last_name = request.POST['Last_Name']
             changingAccount.phone_number = request.POST['Phone']
             changingAccount.gender = request.POST['Gender']
             changingAccount.email = request.POST['Email']
             changingAccount.description = request.POST['Description']
             changingAccount.save()


             updateAccountAds(changingAccount)
             updateAccountTeams(changingAccount)
         
    return redirect('accounts:account', accountName)


@login_required(login_url=login_path)
def accountAdvertisements(request, accountName):
    advertisementList = Advertisements.objects.filter(owner = Accounts.objects.get(accountName = accountName).id).all()
    print("sport")
    print(advertisementList[0].sport)

    myFilter = AdvertisementsOwnFilter(request.GET, queryset = advertisementList)
    advertisementList = myFilter.qs
    print("my filter")
    print(myFilter)

    return render(request, 'accounts/viewOwnAdvertisements.html', {'advertisementList':advertisementList, 'accountName':accountName, 'myFilter':myFilter})

@login_required(login_url=login_path)
def accountTeams(request, accountName):

    teamsList = Teams.objects.filter(owner = Accounts.objects.get(accountName = accountName).id).all()
    return render(request, 'accounts/viewOwnTeams.html', {'teamsList':teamsList, 'accountName':accountName})

@login_required(login_url=login_path)
def accountOrganisations(request, accountName):

    orgsList = Organisations.objects.filter(owner = Accounts.objects.get(accountName = accountName).id).all()
    return render(request, 'accounts/viewOwnOrganisations.html', {'orgsList':orgsList, 'accountName':accountName})

@login_required(login_url=login_path)
def accountOrganisationsDelete(request, accountName, orgID):

    Organisations.objects.get(id=orgID).delete()

    return redirect('accounts:accountTeams', accountName)
    return render(request, 'accounts/viewOwnOrganisations.html', {'orgsList':orgsList, 'accountName':accountName})




@login_required(login_url=login_path)
def accountOrganisationsEdit(request, accountName):

    orgsList = Organisations.objects.filter(owner = Accounts.objects.get(accountName = accountName).id).all()
    return render(request, 'accounts/viewOwnOrganisations.html', {'orgsList':orgsList, 'accountName':accountName})


@login_required(login_url=login_path)
def accountTeamsEdit(request, accountName, teamID):

    sportsList = Sports.objects.all()
    team = Teams.objects.get(id = teamID)
    startHour = converTimeToClockTime(team.startTimeRange.hour)
    startMinute = converTimeToClockTime(team.startTimeRange.minute)
    endHour = converTimeToClockTime(team.endTimeRange.hour)
    endMinute = converTimeToClockTime(team.endTimeRange.minute)
    return render(request, 'accounts/editTeam.html', {'team': team, 'sportsList':sportsList, 'accountName':accountName,
    'startHour':startHour, 'startMinute':startMinute, 'endHour':endHour, 'endMinute':endMinute,
    'listOfDaysInWeek':listOfDaysInWeek, 'listOfGenderOptions':listOfGenderOptions})

@login_required(login_url=login_path)
def accountTeamsEditMedium(request, accountName, teamID):
    if request.user.username == Teams.objects.get(id=teamID).owner.accountName:
        team = Teams.objects.get(id = teamID)

        nameOfOrg = request.POST['organisationName']
        postName = request.POST['fname']
        firstTime = request.POST['start-time'].split(':',2)
        lastTime =  request.POST['end-time'].split(':',2)
        sport =  request.POST['Sport']
        team.teamName = postName
        team.day =  request.POST['Days']
        team.location =  request.POST['teamLocation']
        team.lengthOfGame =  request.POST['lengthOfGame']
        team.startTimeRange = datetime.time(int(firstTime[0]), int(firstTime[1]), 0)
        team.endTimeRange = datetime.time(int(lastTime[0]), int(lastTime[1]), 0)
        team.owner = Accounts.objects.get(accountName = request.user.username)
        team.sport = sport
        team.currentNumPlayers = request.POST['currentPlayers']
        team.lookingNumPlayers = request.POST['lookingPlayers']
        team.lookingGenderPlayers = request.POST['genderRequirements']
        team.notes  = request.POST['Notes']
        team.save()
        print("team edited successfully")
    else:
        print("team not edited successfully")
    return redirect('accounts:accountTeams', accountName)

@login_required(login_url=login_path)
def accountTeamsDelete(request, accountName, teamID):

    team = Teams.objects.get(id = teamID)
    teamsList = Teams.objects.filter(owner = Accounts.objects.get(accountName = accountName).id).all()
    return render(request, 'accounts/deleteTeam.html', {'teamsList':teamsList, 'team':team, 'accountName':accountName})

@login_required(login_url=login_path)
def accountTeamsDeleteMedium(request, accountName, teamID):
    if request.user.username == Teams.objects.get(id=teamID).owner.accountName:
        Teams.objects.get(id=teamID).delete()
        print("Team deleted")
    else:
        print("team not deleted")
    return redirect('accounts:accountTeams', accountName)

@login_required(login_url=login_path)
def accountAdEdit(request, accountName, adID):
    ad = Advertisements.objects.get(id = adID)
    days = ad.days
    sports = ad.sport
    print('ad days')
    print(ad.days)
    print('ad sport')
    print(ad.sport)
    print(days)
    print(listOfDaysInWeek)
    sportsList = Sports.objects.all()
    startHour = converTimeToClockTime(ad.EarliestTime.hour)
    startMinute = converTimeToClockTime(ad.EarliestTime.minute)
    endHour = converTimeToClockTime(ad.LatestTime.hour)
    endMinute = converTimeToClockTime(ad.LatestTime.minute)
    return render(request, 'accounts/editAd.html', {'ad': ad,'selectedSports':sports, 'sportsList':sportsList, 'accountName':accountName,
    'startHour':startHour, 'startMinute':startMinute, 'endHour':endHour, 'endMinute':endMinute, 'days':days,'listOfDaysInWeek':listOfDaysInWeek})

@login_required(login_url=login_path)
def accountAdEditMedium(request, accountName, adID):
    if request.user.username == Advertisements.objects.get(id=adID).owner.accountName:
        print("Form in medium")
        print(request.POST)
        ad = Advertisements.objects.get(id = adID)
        notes  = request.POST['Notes']
        ad.notes = notes
        ad.save()
        print("account eddited succesfully")
    else:
        print("account did not edit succesfully")
    return redirect('accounts:accountAdvertisements', accountName)

@login_required(login_url=login_path)
def accountAdDelete(request, accountName, adID):

    ad = Advertisements.objects.get(id = adID)

accounts/templates/accounts/addAdvertisement.html
{% extends 'base_layout.html' %}
{% block content %}
{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}
<!DOCTYPE html>
<html>
<h2>You are advertising yourself to join a team!</h2>
<body>
  <form action="{% url 'organisation:addAdvertisementMedium' nameOfOrg %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">

    <label for="Day" >Day:</label><br>
    <select name="Days" required size="7" multiple>
       <option value="Monday">Monday</option>
       <option value="Tuesday">Tuesday</option>
       <option value="Wednesday">Wednesday</option>
       <option value="Thursday">Thursday</option>
       <option value="Friday">Friday</option>
       <option value="Saturday">Saturday</option>
       <option value="Sunday">Sunday</option>
    </select>

    <br/>
    <p>Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</p>
    <br>


    <label for="Sport" >Sport:</label><br>
    <select name="Sport"  required size="5" multiple>
        {% for sport in sportsList %}
         <option value="{{sport.name}}">{{sport.name}}</option>
        {% endfor %}
    </select>

    <br/>
    <p>Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</p>
    <br>

    <label for="start-time">Earliest Time Available: </label>
    <input id="start-time" type="time" name="start-time" value="13:30">
    <br>
    <label for="end-time">Latest Time Available:   </label>
    <input id="end-time" type="time" name="end-time" value="20:00">
    <br>
    <br>

    <label for="Notes">Any additional notes you want to share. e.g. Positions, grade, experience, etc...</label><br>
    <textarea id="Notes" name="Notes" rows="4" cols="50"></textarea>
    <br>
    <br />

    <input type="submit" value="Submit">

  </form>


<text> Thanks </text>
</body>
{% endif %}
{% endblock content %}

accounts/templates/accounts/deleteAd.html
{% extends 'base_layout.html' %}
{% block content %}
{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}
<!DOCTYPE html>
<html>
<h2>You are deleting one of your advertisements. Nobody else will be able to see it once you delete it.</h2>
<h4> If you click the button, your ad will be deleted. </h4>
<body>
  <form action="{% url 'accounts:accountAdDeleteMedium'  request.user.username ad.id %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">


    <input type="submit" value="Delete">

  </form>



</body>
{% endif %}
{% endblock content %}

accounts/templates/accounts/deleteOrganisation.html
{% extends 'base_layout.html' %}
{% block content %}

{% if request.user.username != accountName%}
  <p> This is not your account </p>
  <p> {{request.user.username}}  = {{accountName}}
{% else %}

<!DOCTYPE html>
<html>
<h2>You are deleting the organisation {{org.OrganisationName}}. Nobody else will be able to see the organisation once you delete it.</h2>
<h4> If you click the button, your organisation will be deleted. </h4>
<body>
  <form action="{% url 'accounts:organisationDeleteMedium'  request.user.username org.id %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">


    <input type="submit" value="Delete">

  </form>



</body>
{% endif %}
{% endblock content %}

accounts/templates/accounts/deleteTeam.html
{% extends 'base_layout.html' %}
{% block content %}

{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}

<!DOCTYPE html>
<html>
<h2>You are deleting the team {{team.teamName}}. Nobody else will be able to see the team once you delete it.</h2>
<h4> If you click the button, your team will be deleted. </h4>
<body>
  <form action="{% url 'accounts:accountTeamsDeleteMedium'  request.user.username team.id %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">
  

    <input type="submit" value="Delete">

  </form>



</body>
{% endif %}
{% endblock content %}

accounts/templates/accounts/editAccount.html
<p> hello </p>

accounts/templates/accounts/editOrganisation.html
{% extends 'base_layout.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>You are editing your organisation named: {{org.OrganisationName}}</h2>
<body>
  <form action="{% url 'accounts:organisationEditMedium'  request.user.username org.id %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <label for="orgName">Organisation Name:</label><br>
    <input type="text" id="orgName" name="orgName" value = "{{org.OrganisationName}}"><br>
    <br>

    <label for="Registration_Link">Put in the link for players and teams to register</label><br>
    <p> Make sure you include "http://" at the start of the address. E.g. "http://www.organisation/signup.com" </p>
      <input type="text" id="Registration_Link" name="Registration_Link" maxlength="100" required value = "{{org.CompetitionRegistrationLink}}"><br>

    <input type="submit" value="Submit">
  </form>

</body>
{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Don't have an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/noAccount.html
{% extends 'base_layout.html' %}
{% block content %}
<p> There is no account with this name.... </p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}

    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <br>
        <br>
        <input type="submit" value="Signup">
    </form>



{% endblock %}

accounts/templates/accounts/viewOwnAdvertisements.html
{% extends 'testing.html' %}


{% block table %}
{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}

<br>
			<form method="get">
				{{myFilter.form}}
		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>
<br>

<table class="table table-bordered">
    <thead>
      <tr>
        <th>Username</th>
        <th>Sports</th>
        <th>Days</th>
        <th>Organisation</th>
        <th>Available Start Time</th>
        <th>Available End Time</th>
        <th>Gender</th>
        <th>Notes</th>
        <th>Ad Id</th>
        <th> Edit Team </th>
        <th> Delete Team </th>
      </tr>
    </thead>
    <tbody>
      {% for ad in advertisementList %}
        <tr>
          <td><a href="{% url 'accounts:account' ad.owner.accountName %}">{{ ad.owner.accountName }}</td>
          <td>{{ad.sport}}</td>
          <td>{{ad.days}}</td>
          <td>{{ad.org.OrganisationName}} </td>
          <td>{{ ad.EarliestTime}}</td>
          <td>{{ ad.LatestTime}}</td>
          <td>{{ ad.owner.gender}}</td>
          <td>{{ ad.notes}}</td>
          <td>{{ ad.id}}</td>
          <td><a href="{% url 'accounts:accountAdEdit' request.user.username ad.id %}">Edit Ad</td>
          <td><a href="{% url 'accounts:accountAdDelete' request.user.username ad.id %}">Delete Ad</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="15">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

accounts/templates/accounts/viewOwnOrganisations.html
{% extends 'testing.html' %}
{% load admin_list %}

{% block table %}

{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}

<br>

			<form method="get">

				{{myFilter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>

<br>


<h1> You are looking at organisations you have advertised! </h1>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Organisation Name</th>
        <th>Organisation Owner</th>
        <th>Registration Link</th>
        <th>Competitions</th>
        <th>Edit Organisation</th>
        <th>Delete Organisation</th>
        </tr>
    </thead>
    <tbody>
      {% for org in orgsList %}
        <tr>
          <td><a href="{% url 'organisation:organisationHome' org.OrganisationName %}">{{ org.OrganisationName}}</td>
          <td>{{org.owner.accountName}}
          <td>{{org.CompetitionRegistrationLink}}</td>
          <td><a href="{% url 'organisation:viewCompetitions' org.OrganisationName %}"> Competitons </td>
          <td><a href="{% url 'accounts:organisationEdit' accountName org.id %}"> Edit Org </td>
          <td><a href="{% url 'accounts:organisationDelete' accountName org.id %}"> Delete Org </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="16">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}

accounts/templates/accounts/viewOwnTeams.html
{% extends 'testing.html' %}


{% block table %}

{% if request.user.username != accountName%}
  <p> This is not your account </p>
{% else %}

<br>

			<form method="get">

				{{myFilter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>

<br>


<h1> You are looking at teams you have advertised! </h1>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Team Name</th>
        <th>Contact Username</th>
        <th>Organisation</th>
        <th>Sport</th>
        <th>Day</th>
        <th>Start Time</th>
        <th>End Time</th>
        <th>Game Length</th>
        <th>Location </th>
        <th>Current # of Players</th>
        <th>Looking for # of Players</th>
        <th>Gender of Additional Players</th>
        <th>Notes</th>
        <th> Edit Team </th>
        <th> Delete Team </th>

      </tr>
    </thead>
    <tbody>
      {% for team in teamsList %}
        <tr>
          <td>{{ team.teamName}}</td>
          {% if team.owner.accountName == null or team.owner.accountName == ""   %}
          <td></td>
          {% else %}
          <td><a href="{% url 'accounts:account' team.owner.accountName%}">{{ team.owner.accountName}}</td>
          {% endif %}
          <td>{{team.org.OrganisationName}}
          <td>{{ team.sport}}</td>
          <td>{{ team.day}}</td>
          <td>{{ team.startTimeRange}}</td>
          <td>{{ team.endTimeRange}}</td>
          <td>{{ team.lengthOfGame}}</td>
          <td>{{ team.location}}</td>
          <td>{{ team.currentNumPlayers}}</td>
          <td>{{ team.lookingNumPlayers}}</td>
          <td>{{ team.lookingGenderPlayers}}</td>
          <td>{{ team.notes}}</td>
          <td><a href="{% url 'accounts:accountTeamsEdit' request.user.username team.id %}"> Edit Team </td>
          <td><a href="{% url 'accounts:accountTeamsDelete' request.user.username team.id %}"> Delete Team </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="16">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% endif %}
{% endblock %}