articles/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'articles'

urlpatterns = [
    
    url(r'^$', views.article_list, name="list"),
    path('allteams', views.allTeams, name="allTeams"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^organisation/', include('organisation.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url('teams/', include('teams.urls')),
    path('testing', views.testing, name='testing'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from organisation import views
from django.urls import path

app_name = 'organisation'
urlpatterns = [
    #url('', views.displayTeams, name="displayTeams"),

    path('maketeam/<str:nameOfOrg>', views.addTeam, name='addTeam'),
    path('maketeamcompetition/<str:nameOfOrg>/<str:compID>', views.addTeamComp, name='addTeamComp'),
    path('maketeamcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addTeamCompMedium, name='addTeamCompMedium'),
    path('viewteams/<str:nameOfOrg>', views.viewTeams, name='viewTeams'),
    path('maketeam/medium/<str:nameOfOrg>', views.addTeamMedium, name='addTeamMedium'),
    path('jointeam/medium/<str:nameOfOrg>', views.joiningTeamMedium, name='joiningTeamMedium'),

    path('viewCompetitions/<str:nameOfOrg>', views.viewCompetitions, name='viewCompetitions'),
    path('competitionDelete/<str:compID>', views.competitionDelete, name='competitionDelete'),
    path('competitionDelete/medium/<str:compID>', views.competitionDeleteMedium, name='competitionDeleteMedium'),
    path('competitionEdit/<str:compID>', views.editCompetition, name='editCompetition'),
    path('competitionEdit/medium/<str:compID>', views.editCompetitionMedium, name='editCompetitionMedium'),

    path('competition/teamview/<str:nameOfOrg>/<str:compID>', views.viewCompetitionTeams, name='viewCompetitionTeams'),
    path('addCompetitions/<str:nameOfOrg>', views.addCompetitions, name='addCompetitions'),
    path('addCompetitions/medium/<str:nameOfOrg>', views.addCompetitionsMedium, name='addCompetitionsMedium'),

    path('makeadvertisement/<str:nameOfOrg>', views.addAdvertisement, name='addAdvertisement'),
    path('makeadvertisementcompetition/<str:nameOfOrg>/<str:compID>', views.addAdvertisementComp, name='addAdvertisementComp'),
    path('makeadvertisementcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addAdvertisementCompMedium, name='addAdvertisementCompMedium'),
    path('viewadvertisements/<str:nameOfOrg>', views.viewAdvertisements, name='viewAdvertisements'),
    path('viewadvertisementscompetition/<str:nameOfOrg>/<str:compID>', views.viewCompetitionAdvertisements, name='viewCompetitionAdvertisements'),
    path('makeadvertisement/medium/<str:nameOfOrg>', views.addAdvertisementMedium, name='addAdvertisementMedium'),



    path('makeorganisation/medium', views.makeOrgMedium, name='makeOrgMedium'),
    url('makeorganisation/fail', views.makeOrgFail, name="makeOrgFail"),
    url('makeorganisation', views.makeOrg, name="makeOrg"),
    path('home/<str:nameOfOrg>', views.organisationHome, name='organisationHome'),




    url('makeSportMedium', views.makeSportMedium, name="makeSportMedium"),
    url('makeSport', views.makeSport, name="makeSport"),

    url('testHTML', views.testHTML, name="testHTML"),

]

teams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from teams import views
urlpatterns = [

    #url('', views.displayTeams, name="displayTeams"),
    url('joining', views.joiningTeams, name="joiningTeams"),
    url('maketeam', views.makingTeams, name="makingTeams"),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    #comment
    '''
    def save(self, *args, **kwargs):
         super().save(*args, **kwargs)

         img = Image.open(self.image.path)

         if img.height > 300 or img.width > 300:
             output_size = (300, 300)
             img.thumbnail(output_size)
             img.save(self.image.path)
    '''
    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
from teams.models import Teams
from members.models import Members
from organisation.models import Organisations

@login_required(login_url="/accounts/login")
def article_list(request):
    print(request)
    if request.method == 'POST':
        print("THIS IS A POST:")
        print(request.POST)
        try:
            postName = request.POST['fname']
            print(postName)
            team = Teams(teamName = postName, day =  request.POST['teamDay'] , location =  request.POST['teamLocation'],
            lengthOfGame =  request.POST['lengthOfGame'], startTimeRange =  request.POST['startTime'])
            team.save()
        except:
            print("It is not a team")


    try:
        print("look here")
        print(relatedTeam.members.all())
    except:
        print("print didnt work")

    teamsList = Teams.objects.all()
    orgList = Organisations.objects.all()


    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/article_list.html', { 'articles': articles, 'teamsList' : teamsList, 'orgList':orgList})

@login_required(login_url="/accounts/login")
def allTeams(request):
    print(request)
    if request.method == 'POST':
        print("THIS IS A POST:")
        print(request.POST)
        try:
            postName = request.POST['fname']
            print(postName)
            team = Teams(teamName = postName, day =  request.POST['teamDay'] , location =  request.POST['teamLocation'],
            lengthOfGame =  request.POST['lengthOfGame'], startTimeRange =  request.POST['startTime'])
            team.save()
        except:
            print("It is not a team")

#looking here till line 40

        try:

            firstNamee = request.POST['firstName']
            print(firstNamee)
            lastNamee = request.POST['lastName']
            print(lastNamee)
            print('test')
            member = Members(firstName = firstNamee, lastName = lastNamee)
            print("create member")

            member.save()
            print("member saved")
            print("post team name: ")
            print(request.POST)
            team = Teams.objects.get(teamName=request.POST['postTeamName'])
            team.members.add(member)
            print("Do we get to the end?")
            print(team.members)
        except:
            print("it is not a member")

    print("testing")
    #print(request.POST['postTeamName'])
    #relatedTeam = Teams.objects.get(teamName=request.POST['postTeamName'])

    try:
        print("look here")
        print(relatedTeam.members.all())
    except:
        print("print didnt work")

    teamsList = Teams.objects.all()
    orgList = Organisations.objects.all()

    print(teamsList)
    for object in teamsList:
        print(object.teamName)
    print("ids")

    print(Teams.objects.filter(id='1'))

    articles = Article.objects.all().order_by('date');
    return render(request, 'articles/allTeams.html', { 'articles': articles, 'teamsList' : teamsList, 'orgList':orgList})

@login_required(login_url="/accounts/login")
def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

def testing(request, slug):

    return render(request, 'articles/testing.html')

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

articles/templates/articles/allTeams.html
{% extends 'base_layout.html' %}


{% block content%}
<h1>You are in the {{orgName}} organisation home page</h1>

<section class="pricing py-5">
<div class="container">
  <div class="row">
    <!-- Free Tier -->
    {% for team in teamsList %}
    <div class="col-lg-4">
      <div class="card mb-5 mb-lg-0">
        <div class="card-body">
          <h2 style="font-size:30px" class="card-price text-center">{{team.teamName}}<span class="period"></span></h2>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.day}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.startTimeRange}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.lengthOfGame}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.location}}</h5>

          <hr>
          <ul class="fa-ul">
            {% for i in team.members.all %}
            <li><span class="fa-li"><i class="fas fa-check"></i></span>{{i.firstName}} {{i.lastName}}</li>
            {% endfor %}
          </ul>
          <form class = "site-form" action="{% url 'joiningTeams' %}" method = "post">
            {% csrf_token %}
            {{form}}
            <input type="hidden" id="teamName" name='teamName' value = "{{team.teamName}}">
            <input type = "submit"  class="btn btn-block btn-primary text-uppercase" value = "Join Team">

          </form>
        </div>
      </div>
    </div>
    {% endfor %}

{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <h3>Written by {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}

<!--
													<h3>Form</h3>

													<form method="post" action="#">
														<div class="row gtr-uniform">
															<div class="col-6 col-12-xsmall">
																<input type="text" name="demo-name" id="demo-name" value="" placeholder="Name" />
															</div>
															<div class="col-6 col-12-xsmall">
																<input type="email" name="demo-email" id="demo-email" value="" placeholder="Email" />
															</div>

															<div class="col-12">
																<select name="demo-category" id="demo-category">
																	<option value="">- Category -</option>
																	<option value="1">Manufacturing</option>
																	<option value="1">Shipping</option>
																	<option value="1">Administration</option>
																	<option value="1">Human Resources</option>
																</select>
															</div>

															<div class="col-4 col-12-small">
																<input type="radio" id="demo-priority-low" name="demo-priority" checked>
																<label for="demo-priority-low">Low</label>
															</div>
															<div class="col-4 col-12-small">
																<input type="radio" id="demo-priority-normal" name="demo-priority">
																<label for="demo-priority-normal">Normal</label>
															</div>
															<div class="col-4 col-12-small">
																<input type="radio" id="demo-priority-high" name="demo-priority">
																<label for="demo-priority-high">High</label>
															</div>

															<div class="col-6 col-12-small">
																<input type="checkbox" id="demo-copy" name="demo-copy">
																<label for="demo-copy">Email me a copy</label>
															</div>
															<div class="col-6 col-12-small">
																<input type="checkbox" id="demo-human" name="demo-human" checked>
																<label for="demo-human">I am a human</label>
															</div>

															<div class="col-12">
																<textarea name="demo-message" id="demo-message" placeholder="Enter your message" rows="6"></textarea>
															</div>

															<div class="col-12">
																<ul class="actions">
																	<li><input type="submit" value="Send Message" class="primary" /></li>
																	<li><input type="reset" value="Reset" /></li>
																</ul>
															</div>
														</div>
													</form>
												-->
<section class="pricing py-5">
<div class="container">
  <div class="card card-body">

  <div class="row">
      <ul class="fa-ul">
            {% for org in orgList %}

            <li><span class="fa-li"><i class="fas fa-check"></i></span> <a href="{% url 'organisation:organisationHome' org.OrganisationName %}">{{org.OrganisationName}}</a></li>
            {% endfor %}
          </ul>
          </div>
          </div>
          </div>
          </section>


{% endblock %}