accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    path('user/<str:accountName>', views.account, name='account'),
    path('user/<str:accountName>/edit', views.accountEdit, name='accountEdit'),
    path('user/<str:accountName>/editMedium', views.accountEditMedium, name='accountEditMedium'),


    path('user/<str:accountName>/organisations', views.accountOrganisations, name='accountOrganisations'),
    path('user/<str:accountName>/teams', views.accountTeams, name='accountTeams'),
    path('user/<str:accountName>/advertisements', views.accountAdvertisements, name='accountAdvertisements'),

    path('user/<str:accountName>/<str:orgID>/deleteOrganisation', views.organisationDelete, name='organisationDelete'),
    path('user/<str:accountName>/<str:orgID>/deleteOrganisation/medium', views.organisationDeleteMedium, name='organisationDeleteMedium'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation', views.organisationEdit, name='organisationEdit'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation/medium', views.organisationEditMedium, name='organisationEditMedium'),


    path('user/<str:accountName>/<str:teamID>/editTeam', views.accountTeamsEdit, name='accountTeamsEdit'),
    path('user/<str:accountName>/<str:teamID>/editTeam/medium', views.accountTeamsEditMedium, name='accountTeamsEditMedium'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam', views.accountTeamsDelete, name='accountTeamsDelete'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam/medium', views.accountTeamsDeleteMedium, name='accountTeamsDeleteMedium'),

    path('user/<str:accountName>/<str:adID>/editAd', views.accountAdEdit, name='accountAdEdit'),
    path('user/<str:accountName>/<str:adID>/editAd/medium', views.accountAdEditMedium, name='accountAdEditMedium'),
    path('user/<str:accountName>/<str:adID>/deleteAd', views.accountAdDelete, name='accountAdDelete'),
    path('user/<str:accountName>/<str:adID>/deleteAd/medium', views.accountAdDeleteMedium, name='accountAdDeleteMedium'),

]

articles/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'articles'

urlpatterns = [
    
    url(r'^$', views.article_list, name="list"),
    path('allteams', views.allTeams, name="allTeams"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^organisation/', include('organisation.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url('teams/', include('teams.urls')),
    path('testing', views.testing, name='testing'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from organisation import views
from django.urls import path

app_name = 'organisation'
urlpatterns = [
    #url('', views.displayTeams, name="displayTeams"),

    path('maketeam/<str:nameOfOrg>', views.addTeam, name='addTeam'),
    path('maketeamcompetition/<str:nameOfOrg>/<str:compID>', views.addTeamComp, name='addTeamComp'),
    path('maketeamcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addTeamCompMedium, name='addTeamCompMedium'),
    path('viewteams/<str:nameOfOrg>', views.viewTeams, name='viewTeams'),
    path('maketeam/medium/<str:nameOfOrg>', views.addTeamMedium, name='addTeamMedium'),
    path('jointeam/medium/<str:nameOfOrg>', views.joiningTeamMedium, name='joiningTeamMedium'),

    path('viewCompetitions/<str:nameOfOrg>', views.viewCompetitions, name='viewCompetitions'),
    path('competitionDelete/<str:compID>', views.competitionDelete, name='competitionDelete'),
    path('competitionDelete/medium/<str:compID>', views.competitionDeleteMedium, name='competitionDeleteMedium'),
    path('competitionEdit/<str:compID>', views.editCompetition, name='editCompetition'),
    path('competitionEdit/medium/<str:compID>', views.editCompetitionMedium, name='editCompetitionMedium'),

    path('competition/teamview/<str:nameOfOrg>/<str:compID>', views.viewCompetitionTeams, name='viewCompetitionTeams'),
    path('addCompetitions/<str:nameOfOrg>', views.addCompetitions, name='addCompetitions'),
    path('addCompetitions/medium/<str:nameOfOrg>', views.addCompetitionsMedium, name='addCompetitionsMedium'),

    path('makeadvertisement/<str:nameOfOrg>', views.addAdvertisement, name='addAdvertisement'),
    path('makeadvertisementcompetition/<str:nameOfOrg>/<str:compID>', views.addAdvertisementComp, name='addAdvertisementComp'),
    path('makeadvertisementcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addAdvertisementCompMedium, name='addAdvertisementCompMedium'),
    path('viewadvertisements/<str:nameOfOrg>', views.viewAdvertisements, name='viewAdvertisements'),
    path('viewadvertisementscompetition/<str:nameOfOrg>/<str:compID>', views.viewCompetitionAdvertisements, name='viewCompetitionAdvertisements'),
    path('makeadvertisement/medium/<str:nameOfOrg>', views.addAdvertisementMedium, name='addAdvertisementMedium'),



    path('makeorganisation/medium', views.makeOrgMedium, name='makeOrgMedium'),
    url('makeorganisation/fail', views.makeOrgFail, name="makeOrgFail"),
    url('makeorganisation', views.makeOrg, name="makeOrg"),
    path('home/<str:nameOfOrg>', views.organisationHome, name='organisationHome'),




    url('makeSportMedium', views.makeSportMedium, name="makeSportMedium"),
    url('makeSport', views.makeSport, name="makeSport"),

    url('testHTML', views.testHTML, name="testHTML"),

]

teams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from teams import views
urlpatterns = [

    #url('', views.displayTeams, name="displayTeams"),
    url('joining', views.joiningTeams, name="joiningTeams"),
    url('maketeam', views.makingTeams, name="makingTeams"),
]

templates/CompetitionTeams.html
{% extends 'base_layout.html' %}


{% block test %}
<div class="row">
 <div class="col-md">
   <div class="card card-body">
     <h5>{{nameOfOrg}}</h5>
     <hr>
     <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'organisation:organisationHome' nameOfOrg %}">Organisation Home Page</a>
     <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:account' request.user.username %}">Organisation Contact</a>

   </div>
 </div>

 <div class="col-md">
   <div class="card card-body">
     <h5>Competitions</h5>
     <hr>
      <a class="btn btn-outline-info  btn-sm btn-block" href="">Our Competitions</a>
     <a class="btn btn-outline-info  btn-sm btn-block" href="">Registration Link</a>
   </div>
 </div>

 <div class="col-md">
   <div class="card card-body">
     <h5>Advertise</h5>
     <hr>
       <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:account' request.user.username %}">Advertise Your Team</a>

		  <a class="btn btn-outline-info  btn-sm btn-block"  href="{% url 'accounts:accountAdvertisements' request.user.username %}">Advertise Yourself</a>

   </div>
 </div>
</div>

<main role="main" class="container">
  <div class="row">
    <div class="col-xl-12 align-self-center">
      {% block content %}{% endblock %}
    </div>

    <br>


     <br>

       <div class="card card-body">
          {% block table %}

          {% endblock %}
        </div>

</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<br>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/static/css/stylesheet.css" />


    <style>

    body {
      background: #fafafa;
      color: #111111;
      margin-top: 5rem;
    }

    h1, h2, h3, h4, h5, h6 {
      color: #444444;
    }
    h1 {text-align: center;}

    ul {
      margin: 0;
    }

    .bg-steel {
      background-color:#3c6a6d;
    }

    .site-header .navbar-nav .nav-link {
      color: #ffffff;
    }

    .site-header .navbar-nav .nav-link:hover {
      color: #ffffff;
    }

    .site-header .navbar-nav .nav-link.active {
      font-weight: 500;
    }

    .content-section {
      background: #ffffff;
      padding: 10px 20px;
      border: 1px solid #dddddd;
      border-radius: 3px;
      margin-bottom: 20px;
    }

    .article-title {
      color: #444444;
    }

    a.article-title:hover {
      color: #428bca;
      text-decoration: none;
    }

    .article-content {
      white-space: pre-line;
    }

    .article-img {
      height: 65px;
      width: 65px;
      margin-right: 16px;
    }

    .article-metadata {
      padding-bottom: 1px;
      margin-bottom: 4px;
      border-bottom: 1px solid #e3e3e3
    }

    .article-metadata a:hover {
      color: #333;
      text-decoration: none;
    }

    .article-svg {
      width: 25px;
      height: 25px;
      vertical-align: middle;
    }

    .account-img {
      height: 125px;
      width: 125px;
      margin-right: 20px;
      margin-bottom: 16px;
    }

    .account-heading {
      font-size: 2.5rem;
    }

    /* Teams CSS */


    .pricing .card {
      border: none;
      border-radius: 1rem;
      transition: all 0.2s;
      box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .pricing hr {
      margin: 1.5rem 0;
    }

    .pricing .card-title {
      margin: 0.5rem 0;
      font-size: 0.9rem;
      letter-spacing: .1rem;
      font-weight: bold;
    }

    .pricing .card-price {
      font-size: 3rem;
      margin: 0;
    }

    .pricing .card-price .period {
      font-size: 0.8rem;
    }

    .pricing ul li {
      margin-bottom: 1rem;
    }

    .pricing .text-muted {
      opacity: 0.7;
    }

    .pricing .btn {
      font-size: 80%;
      border-radius: 5rem;
      letter-spacing: .1rem;
      font-weight: bold;
      padding: 1rem;
      opacity: 0.7;
      transition: all 0.2s;
    }

/* Hover Effects on Card */

@media (min-width: 992px) {
  .pricing .card:hover {
    margin-top: -.25rem;
    margin-bottom: .25rem;
    box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.3);
  }
  .pricing .card:hover .btn {
    opacity: 1;
  }
}



.site-footer
{
  background-color:#3c6a6d;
  padding:45px 0 20px;
  font-size:15px;
  line-height:24px;
  color:#bff3dd;
}
.site-footer hr
{
  border-top-color:#bbb;
  opacity:0.5
}
.site-footer hr.small
{
  margin:20px 0
}
.site-footer h6
{
  color:#fff;
  font-size:16px;
  text-transform:uppercase;
  margin-top:5px;
  letter-spacing:2px
}
.site-footer a
{
  color:#737373;
}
.site-footer a:hover
{
  color:#3366cc;
  text-decoration:none;
}
.footer-links
{
  padding-left:0;
  list-style:none
}
.footer-links li
{
  display:block
}
.footer-links a
{
  color:#bff3dd
}
.footer-links a:active,.footer-links a:focus,.footer-links a:hover
{
  color:#ffffff;
  text-decoration:none;
}
.footer-links.inline li
{
  display:inline-block
}
.site-footer .social-icons
{
  text-align:right
}
.site-footer .social-icons a
{
  width:40px;
  height:40px;
  line-height:40px;
  margin-left:6px;
  margin-right:0;
  border-radius:100%;
  background-color:#33353d
}
.copyright-text
{
  margin:0
}
@media (max-width:991px)
{
  .site-footer [class^=col-]
  {
    margin-bottom:30px
  }
}
@media (max-width:767px)
{
  .site-footer
  {
    padding-bottom:0
  }
  .site-footer .copyright-text,.site-footer .social-icons
  {
    text-align:center
  }
}



    </style>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'home' %}">Jake's Netball</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">


            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'articles:list' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'organisation:testHTML' %}">Test HTML</a>
              <a class="nav-item nav-link" href="{% url 'organisation:makeSport' %}">Make Sport</a>
              <a class="nav-item nav-link" href="{% url 'organisation:makeOrg' %}">Make Organisation</a>

              {% if request.user.username == null or request.user.username == ""   %}
              <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
              {% else %}
              <a class="nav-item nav-link" href="{% url 'accounts:account' request.user.username %}">{{request.user.username}}</a>
              {% endif %}
              <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
              <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Make Account</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <div id="sidebar">
      <div class="inner">

        <!-- Search -->
          <section id="search" class="alt">
            <form method="post" action="#">
              <input type="text" name="query" id="query" placeholder="Search" />
            </form>
          </section>

        <!-- Menu -->
          <nav id="menu">
            <header class="major">
              <h2>Menu</h2>
            </header>
            <ul>
              <li><a href="index.html">Homepage</a></li>
              <li><a href="generic.html">Generic</a></li>
              <li><a href="elements.html">Elements</a></li>
              <li>
                <span class="opener">Submenu</span>
                <ul>
                  <li><a href="#">Lorem Dolor</a></li>
                  <li><a href="#">Ipsum Adipiscing</a></li>
                  <li><a href="#">Tempus Magna</a></li>
                  <li><a href="#">Feugiat Veroeros</a></li>
                </ul>
              </li>
              <li><a href="#">Etiam Dolore</a></li>
              <li><a href="#">Adipiscing</a></li>
              <li>
                <span class="opener">Another Submenu</span>
                <ul>
                  <li><a href="#">Lorem Dolor</a></li>
                  <li><a href="#">Ipsum Adipiscing</a></li>
                  <li><a href="#">Tempus Magna</a></li>
                  <li><a href="#">Feugiat Veroeros</a></li>
                </ul>
              </li>
              <li><a href="#">Maximus Erat</a></li>
              <li><a href="#">Sapien Mauris</a></li>
              <li><a href="#">Amet Lacinia</a></li>
            </ul>
          </nav>
        </div>
      </div>

    <main role="main" class="container">
      <div class="row">
        <div class="col-xl-12 align-self-center">
          {% block test %}{% endblock %}
          {% block content %}{% endblock %}
          {% block orgAdvertisementsAndTeams %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->


</body>
<br>
<br>
<br>
<br>
<br>

<footer class="site-footer">
     <div class="container">
       <div class="row">
         <div class="col-sm-12 col-md-6">
           <h6>About</h6>
           <p class="text-justify">This website helps connect sports teams and individuals! Find the organisation you are looking to play in and:
             <UL><UL>
           <li>Find teams looking for players</li>
           <li>Find players looking for teams</li>
           <li>Advertise your team to players</li>
           <li>Advertise yourself to teams</li>
            </UL></UL></p>
         </div>

         <div class="col-xs-6 col-md-3">
           <h6>Quick Links</h6>
           <ul class="footer-links">
             <li><a href="">How To Use</a></li>
             <li><a href="">Signup</a></li>
             <li><a href="">Organisations</a></li>
           </ul>
         </div>

         <div class="col-xs-6 col-md-3">
           <h6>Other</h6>
           <ul class="footer-links">
             <li><a href="">Privacy Policy</a></li>
             <li><a href="">Contact</a></li>
             <li><a href="">Why</a></li>
           </ul>
         </div>
       </div>
       <hr>
     </div>
     <div class="container">
       <div class="row">
         <div class="col-md-8 col-sm-6 col-xs-12">
           <p class="copyright-text">Copyright &copy; 2020 All Rights Reserved by Jake</p>
         </div>

       </div>
     </div>
</footer>


</html>

templates/testing.html
{% extends 'base_layout.html' %}


{% block test %}

<div class="row">
 <div class="col-md">
   <div class="card card-body">
     <h5>Competitions</h5>
     <hr>
      <a class="btn btn-outline-info  btn-sm btn-block" href="https://google.com/">Our Competitions</a>
     <a class="btn btn-outline-info  btn-sm btn-block" href="{{org.CompetitionRegistrationLink}}">Registration Link</a>
   </div>
 </div>

 <div class="col-md">
   <div class="card card-body">
     <h5>Your Account</h5>
     <hr>
       <a class="btn btn-outline-info  btn-sm btn-block" href="{% url 'accounts:account' request.user.username %}">{{request.user.username}}</a>
		  <a class="btn btn-outline-info  btn-sm btn-block"  href="{% url 'accounts:accountAdvertisements' request.user.username %}">Your Advertisements</a>

   </div>
 </div>
</div>

<main role="main" class="container">
  <div class="row">
    <div class="col-xl-12 align-self-center">
      {% block content %}{% endblock %}
    </div>

    <br>


     <br>

       <div class="card card-body">
          {% block table %}

          {% endblock %}
        </div>

</main>


<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<br>
{% endblock %}