accounts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    path('user/<str:accountName>', views.account, name='account'),
    path('user/<str:accountName>/edit', views.accountEdit, name='accountEdit'),
    path('user/<str:accountName>/editMedium', views.accountEditMedium, name='accountEditMedium'),


    path('user/<str:accountName>/organisations', views.accountOrganisations, name='accountOrganisations'),
    path('user/<str:accountName>/teams', views.accountTeams, name='accountTeams'),
    path('user/<str:accountName>/advertisements', views.accountAdvertisements, name='accountAdvertisements'),

    path('user/<str:accountName>/<str:orgID>/deleteOrganisation', views.organisationDelete, name='organisationDelete'),
    path('user/<str:accountName>/<str:orgID>/deleteOrganisation/medium', views.organisationDeleteMedium, name='organisationDeleteMedium'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation', views.organisationEdit, name='organisationEdit'),
    path('user/<str:accountName>/<str:orgID>/editOrganisation/medium', views.organisationEditMedium, name='organisationEditMedium'),


    path('user/<str:accountName>/<str:teamID>/editTeam', views.accountTeamsEdit, name='accountTeamsEdit'),
    path('user/<str:accountName>/<str:teamID>/editTeam/medium', views.accountTeamsEditMedium, name='accountTeamsEditMedium'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam', views.accountTeamsDelete, name='accountTeamsDelete'),
    path('user/<str:accountName>/<str:teamID>/deleteTeam/medium', views.accountTeamsDeleteMedium, name='accountTeamsDeleteMedium'),

    path('user/<str:accountName>/<str:adID>/editAd', views.accountAdEdit, name='accountAdEdit'),
    path('user/<str:accountName>/<str:adID>/editAd/medium', views.accountAdEditMedium, name='accountAdEditMedium'),
    path('user/<str:accountName>/<str:adID>/deleteAd', views.accountAdDelete, name='accountAdDelete'),
    path('user/<str:accountName>/<str:adID>/deleteAd/medium', views.accountAdDeleteMedium, name='accountAdDeleteMedium'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from django.urls import path

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^organisation/', include('organisation.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
    url('teams/', include('teams.urls')),
    path('testing', views.testing, name='testing'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

organisation/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from organisation import views
from django.urls import path

app_name = 'organisation'
urlpatterns = [
    #url('', views.displayTeams, name="displayTeams"),

    path('maketeam/<str:nameOfOrg>', views.addTeam, name='addTeam'),
    path('maketeamcompetition/<str:nameOfOrg>/<str:compID>', views.addTeamComp, name='addTeamComp'),
    path('maketeamcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addTeamCompMedium, name='addTeamCompMedium'),
    path('viewteams/<str:nameOfOrg>', views.viewTeams, name='viewTeams'),
    path('maketeam/medium/<str:nameOfOrg>', views.addTeamMedium, name='addTeamMedium'),
    path('jointeam/medium/<str:nameOfOrg>', views.joiningTeamMedium, name='joiningTeamMedium'),

    path('viewCompetitions/<str:nameOfOrg>', views.viewCompetitions, name='viewCompetitions'),
    path('competitionDelete/<str:compID>', views.competitionDelete, name='competitionDelete'),
    path('competitionDelete/medium/<str:compID>', views.competitionDeleteMedium, name='competitionDeleteMedium'),
    path('competitionEdit/<str:compID>', views.editCompetition, name='editCompetition'),
    path('competitionEdit/medium/<str:compID>', views.editCompetitionMedium, name='editCompetitionMedium'),

    path('competition/teamview/<str:nameOfOrg>/<str:compID>', views.viewCompetitionTeams, name='viewCompetitionTeams'),
    path('addCompetitions/<str:nameOfOrg>', views.addCompetitions, name='addCompetitions'),
    path('addCompetitions/medium/<str:nameOfOrg>', views.addCompetitionsMedium, name='addCompetitionsMedium'),

    path('makeadvertisement/<str:nameOfOrg>', views.addAdvertisement, name='addAdvertisement'),
    path('makeadvertisementcompetition/<str:nameOfOrg>/<str:compID>', views.addAdvertisementComp, name='addAdvertisementComp'),
    path('makeadvertisementcompetition/medium/<str:nameOfOrg>/<str:compID>', views.addAdvertisementCompMedium, name='addAdvertisementCompMedium'),
    path('viewadvertisements/<str:nameOfOrg>', views.viewAdvertisements, name='viewAdvertisements'),
    path('viewadvertisementscompetition/<str:nameOfOrg>/<str:compID>', views.viewCompetitionAdvertisements, name='viewCompetitionAdvertisements'),
    path('makeadvertisement/medium/<str:nameOfOrg>', views.addAdvertisementMedium, name='addAdvertisementMedium'),



    path('makeorganisation/medium', views.makeOrgMedium, name='makeOrgMedium'),
    url('makeorganisation/fail', views.makeOrgFail, name="makeOrgFail"),
    url('makeorganisation', views.makeOrg, name="makeOrg"),
    path('home/<str:nameOfOrg>', views.organisationHome, name='organisationHome'),




    url('makeSportMedium', views.makeSportMedium, name="makeSportMedium"),
    url('makeSport', views.makeSport, name="makeSport"),

    url('testHTML', views.testHTML, name="testHTML"),

]

teams/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from teams import views
urlpatterns = [

    #url('', views.displayTeams, name="displayTeams"),
    url('joining', views.joiningTeams, name="joiningTeams"),
    url('maketeam', views.makingTeams, name="makingTeams"),
]

organisation/views.py
from django.shortcuts import render, redirect
from teams.models import Teams
from members.models import Members
from organisation.models import Organisations
from django.contrib.auth.decorators import login_required
from accounts.models import Accounts, Advertisements
from sports.models import Sports
import datetime
from .filters import AdvertisementsOrganisationFilter, TeamsOrganisationFilter, CompetitionsOrganisationFilter
from .models import Organisations, Competitions
from accounts.accountFunctions import listOfGenderOptions
from accounts.accountFunctions import *

# Create your views here.

login_path = "/accounts/login"
@login_required(login_url=login_path)
def organisationHome(request, nameOfOrg):
    print("nameOfOrg")
    print(nameOfOrg)
    org = Organisations.objects.get(OrganisationName = nameOfOrg)
    return render(request, 'organisation/organisationHome.html',{'orgName':nameOfOrg, 'org':org})

@login_required(login_url=login_path)
def makeOrg(request):
    print("we are in making org - not in medium")
    # return HttpResponse('homepage')
    return render(request, 'organisation/makeOrganisation.html')

@login_required(login_url=login_path)
def makeOrgMedium(request):
    nameOfOrg = 'test'
    if request.method == 'POST':
        try:
            nameOfOrg = request.POST['orgName']
            CompetitionRegistrationLink = request.POST['Registration_Link']
            newORG = Organisations(OrganisationName = nameOfOrg, owner = Accounts.objects.get(accountName = request.user.username),
            CompetitionRegistrationLink = CompetitionRegistrationLink)
            newORG.save()
        except:
            print("Exception, not making org")
            print("It is not making an Org")
            return render(request, 'organisation/OrgMakingFail.html')
    return redirect('organisation:organisationHome', nameOfOrg)

    # return HttpResponse('homepage')

@login_required(login_url=login_path)
def makeOrgFail(request):
    print("do we get in makeOrgFail")
    nameOfOrg = '.'
    return render(request, 'organisation/OrgMakingFail.html', nameOfOrg)

@login_required(login_url=login_path)
def addTeam(request, nameOfOrg):
    print("we are in add Team")
    if request.method == 'POST':
        print("THIS IS A POST:")
        print(request.POST)
        nameOfOrg = request.POST['organisationName']
    sportsList = Sports.objects.all()
    print(nameOfOrg)
    # return HttpResponse('homepage')
    return render(request, 'organisation/addTeam.html', {'nameOfOrg':nameOfOrg, 'sportsList':sportsList})

@login_required(login_url=login_path)
def addTeamMedium(request, nameOfOrg):
    print("WE ARE IN THE MEDIUMMMM")
    if request.method == 'POST':
        print("we are in joining teams")
        try:
            print("Checking if adding team:")
            print(request.POST)
            nameOfOrg = request.POST['organisationName']
            postName = request.POST['fname']
            print(postName)
            print("team day")
            print(request.POST['Days'])
            firstTime = request.POST['start-time'].split(':',2)
            lastTime =  request.POST['end-time'].split(':',2)
            sport =  request.POST['Sport']

            team = Teams(teamName = postName, day =  request.POST['Days'], location =  request.POST['teamLocation'],
            lengthOfGame =  request.POST['lengthOfGame'], startTimeRange = datetime.time(int(firstTime[0]), int(firstTime[1]), 0),
            endTimeRange = datetime.time(int(lastTime[0]), int(lastTime[1]), 0), owner = Accounts.objects.get(accountName = request.user.username)
            , sport = sport, currentNumPlayers = request.POST['currentPlayers'], lookingNumPlayers = request.POST['lookingPlayers'],
            lookingGenderPlayers = request.POST['genderRequirements'], notes  = request.POST['Notes'], org = Organisations.objects.get(OrganisationName = nameOfOrg))
            team.save()

            print("team id")
            print(team.id)
            print("nameOfOrg: ")
            print(nameOfOrg)
            print("before org")
            org = Organisations.objects.get(OrganisationName=nameOfOrg)
            print("after org")
            org.teams.add(team)
        except Exception as e:
            print(e)
            print("not adding a team - something went wrong?")
    # return HttpResponse('homepage')
    return redirect('organisation:organisationHome', nameOfOrg, {'org':org})


@login_required(login_url=login_path)
def addTeamComp(request, nameOfOrg, compID):
    print("we are in add Team")
    if request.method == 'POST':
        print("THIS IS A POST:")
        print(request.POST)
        nameOfOrg = request.POST['organisationName']
    sportsList = Sports.objects.all()
    print(nameOfOrg)
    # return HttpResponse('homepage')
    return render(request, 'organisation/addTeamCompetition.html', {'nameOfOrg':nameOfOrg, 'sportsList':sportsList, 'compID':compID})

@login_required(login_url=login_path)
def addTeamCompMedium(request, nameOfOrg, compID):
    print("WE ARE IN THE MEDIUMMMM")
    if request.method == 'POST':
        print("we are in joining teams for a comp")
        try:
            comp = Competitions.objects.get(id = compID)
            sport = comp.CompetitionSport
            day = comp.CompetitionDay
            location = comp.CompetitionLocation
            length = comp.LengthOfGame
            startTime = comp.CompetitionStartTime
            endTime = comp.CompetitionEndTime

            print("Checking if adding team:")
            print(request.POST)
            nameOfOrg = request.POST['organisationName']
            postName = request.POST['fname']

            team = Teams(teamName = postName, day = day, location = location, lengthOfGame =  length, startTimeRange = startTime,
            endTimeRange = endTime, owner = Accounts.objects.get(accountName = request.user.username), sport = sport,
            currentNumPlayers = request.POST['currentPlayers'], lookingNumPlayers = request.POST['lookingPlayers'],
            lookingGenderPlayers = request.POST['genderRequirements'], notes  = request.POST['Notes'], org = Organisations.objects.get(OrganisationName = nameOfOrg),
            TeamCompetiton = comp)
            team.save()

            org = Organisations.objects.get(OrganisationName=nameOfOrg)
            org.teams.add(team)
        except Exception as e:
            print(e)
            print("not adding a team - something went wrong?")
    # return HttpResponse('homepage')
    return redirect('organisation:organisationHome', nameOfOrg)

@login_required(login_url=login_path)
def addAdvertisement(request, nameOfOrg):
    # return HttpResponse('homepage')
    sportsList = Sports.objects.all()
    print(sportsList)
    return render(request, 'organisation/addAdvertisement.html', {'nameOfOrg':nameOfOrg, 'sportsList':sportsList})

@login_required(login_url=login_path)
def addAdvertisementComp(request, nameOfOrg, compID):
    # return HttpResponse('homepage')
    sportsList = Sports.objects.all()
    print(sportsList)
    return render(request, 'organisation/addAdvertisementComp.html', {'nameOfOrg':nameOfOrg, 'sportsList':sportsList, 'compID':compID})

@login_required(login_url=login_path)
def addAdvertisementCompMedium(request, nameOfOrg, compID):
    #this method saves the advertisement information in the database
    print("In advertisement medium comp")
    print(request.POST)
    comp = Competitions.objects.get(id = compID)

    sport = comp.CompetitionSport
    days = comp.CompetitionDay
    earlyTime = comp.CompetitionStartTime
    lateTime = comp.CompetitionEndTime
    notes = request.POST['Notes']
    owner = Accounts.objects.get(accountName = request.user.username)
    gender = owner.gender
    ownerFirstName = owner.first_name
    ownerLastName = owner.last_name

    org = Organisations.objects.get(OrganisationName=nameOfOrg)
    try:
        FillIn = request.POST['FillIn']
    except:
        FillIn = False

    try:
        Permanent = request.POST['permanent']
    except:
        Permanent = False

    print("Fill in")
    print(FillIn)
    print(" permanent ")
    print(Permanent)

    advertisement = Advertisements(org = org, EarliestTime = earlyTime, LatestTime = lateTime,sport = sport, days = days, gender = gender,
    owner = owner, notes = notes, AdvertisementCompetiton = comp, FillIn = FillIn, Permanent = Permanent, ownerFirstName = ownerFirstName, ownerLastName = ownerLastName)

    advertisement.save()
    # return HttpResponse('homepage')
    return redirect('organisation:organisationHome', nameOfOrg)

@login_required(login_url=login_path)
def addAdvertisementMedium(request, nameOfOrg):
    #this method saves the advertisement information in the database
    print("In advertisement medium")
    print(request.POST)
    try:
        daysList = request.POST.getlist('Days')
    except:
        daysList = []
    try:
        sportsList = request.POST.getlist('Sport')
    except:
        sportsList = []


    firstTime = request.POST['start-time'].split(':',2)
    earlyTime = datetime.time(int(firstTime[0]), int(firstTime[1]), 0)
    endTime = request.POST['end-time'].split(':',2)
    lateTime = datetime.time(int(endTime[0]), int(endTime[1]), 0)

    notes = request.POST['Notes']
    owner = Accounts.objects.get(accountName = request.user.username)
    gender = owner.gender
    org = Organisations.objects.get(OrganisationName=nameOfOrg)



    advertisement = Advertisements(org = org, EarliestTime = earlyTime, LatestTime = lateTime,sport = sportsList, days = daysList, gender = gender, owner = owner, notes = notes)

    advertisement.save()
    # return HttpResponse('homepage')
    return redirect('organisation:organisationHome', nameOfOrg, {'org':org})

@login_required(login_url=login_path)
def viewAdvertisements(request, nameOfOrg):
    # delete this view
    advertisementList = Advertisements.objects.filter(org = Organisations.objects.get(OrganisationName=nameOfOrg).id)

organisation/templates/organisation/OrgMakingFail.html
{% extends 'base_layout.html' %}


{% block content %}
<br>

		<h1> I think you tried to make an organisation with a duplicate name </h1>
		<br>
		<h1> Try again with a different name </h1>
{% endblock %}

organisation/templates/organisation/addAdvertisement.html
{% extends 'base_layout.html' %}
{% block content %}
<!DOCTYPE html>
<html>
<h2>You are advertising yourself to join a team!</h2>
<body>
  <form action="{% url 'organisation:addAdvertisementMedium' nameOfOrg %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">

    <label for="Day" >Day:</label><br>
    <select name="Days" required size="7" multiple>
       <option value="Monday">Monday</option>
       <option value="Tuesday">Tuesday</option>
       <option value="Wednesday">Wednesday</option>
       <option value="Thursday">Thursday</option>
       <option value="Friday">Friday</option>
       <option value="Saturday">Saturday</option>
       <option value="Sunday">Sunday</option>
    </select>

    <br/>
    <p>Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</p>
    <br>


    <label for="Sport" >Sport:</label><br>
    <select name="Sport"  required size="5" multiple>
        {% for sport in sportsList %}
         <option value="{{sport.name}}">{{sport.name}}</option>
        {% endfor %}
    </select>

    <br/>
    <p>Hold down the Ctrl (windows) / Command (Mac) button to select multiple options.</p>
    <br>

    <label for="start-time">Earliest Time Available: </label>
    <input id="start-time" type="time" name="start-time" value="13:30">
    <br>
    <label for="end-time">Latest Time Available:   </label>
    <input id="end-time" type="time" name="end-time" value="20:00">
    <br>
    <br>

    <label for="Notes">Any additional notes you want to share. e.g. Positions, grade, experience, etc...</label><br>
    <textarea id="Notes" name="Notes" rows="4" cols="50"></textarea>
    <br>
    <br />

    <input type="submit" value="Submit">

  </form>


<text> Thanks </text>
</body>
{% endblock content %}

organisation/templates/organisation/addCompetition.html
{% extends 'base_layout.html' %}
{% block content %}
<p> {{request.user.username}}  {{orgOwner}}    </p>
{% if request.user.username != orgOwner%}
  <p> This is not your account </p>
{% else %}
<!DOCTYPE html>
<html>
<h2>You are adding a competition!</h2>
<body>
  <form action="{% url 'organisation:addCompetitionsMedium' nameOfOrg %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">

    <label for="Day" >Day:</label><br>
    <select name="Days" required size="7">
       <option value="Monday">Monday</option>
       <option value="Tuesday">Tuesday</option>
       <option value="Wednesday">Wednesday</option>
       <option value="Thursday">Thursday</option>
       <option value="Friday">Friday</option>
       <option value="Saturday">Saturday</option>
       <option value="Sunday">Sunday</option>
    </select>


    <br>
    <br>

    <label for="Sport" >Sport:</label><br>
    <select name="Sport"  required size="5">
        {% for sport in sportsList %}
         <option value="{{sport.name}}">{{sport.name}}</option>
        {% endfor %}
    </select>

    <br>
    <br>
    <label for="start-date">What date does the competition start?</label><br>
    <input type="date" id="start-date" name="start-date"
       min="2020-07-01" max="2023-01-01" required>

    <br>
    <br>
    <label for="end-date">What date does the competition end?</label><br>
    <input type="date" id="end-date" name="end-date"
       min="2020-07-01" max="2023-01-01" required>

       <br>
       <br>

       <br />
       <label for="start-time">Competition Start Time: </label>
       <input id="start-time" type="time" name="start-time" value = "00:00" required>
       <br>
       <label for="end-time">Competition Finish Time:   </label>
       <input id="end-time" type="time" name="end-time" value = "12:00" required>
       <br>
       <br>


       <label for="length">How long are the games? e.g. 40 min, 1 hour, etc</label><br>
         <input type="text" id="length" name="length" maxlength="10" required><br>

    <br>

    <label for="Grade">What grade is this competition? A, B, 1, 2, Social, etc...</label><br>
      <input type="text" id="Grade" name="Grade" value = "Social" maxlength="10" required><br>
    <br>
    <br />

    <label for="Location">What is the location?</label><br>
      <input type="text" id="Location" name="Location" maxlength="30" required><br>
    <br>
    <br />

    

    <label for="Gender" >Gender requirement:</label><br>
    <select name="Gender" required size="3">
      {% for gender in genderList %}
       <option  value="{{gender}}">{{gender}}</option>
      {% endfor %}
    </select>
    <br />
    <br>

    <input type="submit" value="Submit">

  </form>


<text> Thanks </text>
</body>
{% endif %}
{% endblock content %}

organisation/templates/organisation/deleteCompetition.html
{% extends 'base_layout.html' %}
{% block content %}

{% if request.user.username != comp.CompetitionOrganisation.owner.accountName%}
  <p> This is not your account </p>
{% else %}

<!DOCTYPE html>
<html>
<h2>You are deleting a competition in your organisation: {{org.OrganisationName}}. Nobody else will be able to see the competition once you delete it.</h2>
<h4> If you click this button, your competition will be deleted. All other competitions in your organisation will remain visible.</h4>
<body>
  <form action="{% url 'organisation:competitionDeleteMedium' comp.id %}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <input type="hidden" id="organisationName" name='organisationName' value = "{{nameOfOrg}}">

    <input type="submit" value="Delete">

  </form>



</body>
{% endif %}
{% endblock content %}

organisation/templates/organisation/makeOrganisation.html
{% extends 'base_layout.html' %}
{% block content %}
<!DOCTYPE html>
{% load static %}
<head>
      <!--  <link rel="stylesheet" type="text/css" href="/static/css/stylesheet.css" /> -->

</head>
<html>
<h2> Test </h2>
<div class="container">
  <div class="card card-body">
<h2>Enter Organisation Name:</h2>
<body>
  <form action="{% url 'organisation:makeOrgMedium'%}" target="_self" method="post">
    {% csrf_token %}
    {{form}}
    <label for="orgName">Organisation Name:</label><br>
    <input type="text" id="orgName" name="orgName"><br>

    <br>


    <label for="Registration_Link">Put in the link for players and teams to register</label><br>
    <p> Make sure you include "http://" at the start of the address. E.g. "http://www.organisation/signup.com" </p>
      <input type="text" id="Registration_Link" name="Registration_Link" maxlength="100" required><br>

    <input type="submit" value="Submit">
  </form>

</body>
</div>
</div>
{% endblock content %}

organisation/templates/organisation/organisationHome.html
{% extends 'base_layout.html' %}


{% block content %}

<br>
<h1>You are in the {{orgName}} organisation home page</h1>
<br>

<br>
<p> {{request.user.username}}   {{org.owner.accountName}} </p>
{% if request.user.username == org.owner.accountName%}
<br>
<form class = "site-form" action="{% url 'organisation:addCompetitions' orgName %}" method = "post">
  {% csrf_token %}
  {{form}}
<input type="hidden" id="organisationName" name='organisationName' value = "{{orgName}}">
<input type = "submit"  class="btn btn-block btn-primary text-uppercase" value = "Add Competition">
</form>
{% else %}
{% endif %}

<br>

<form class = "site-form" action="{% url 'organisation:viewCompetitions' orgName %}" method = "post">
  {% csrf_token %}
  {{form}}
<input type="hidden" id="organisationName" name='organisationName' value = "{{orgName}}">
<input type = "submit"  class="btn btn-block btn-primary text-uppercase" value = "View Competitions">
</form>



<section class="pricing py-5">
<div class="container">
  <div class="row">
    <!-- Free Tier -->
    <!--
    {% for team in teamsList %}
    <div class="col-lg-4">
      <div class="card mb-5 mb-lg-0">
        <div class="card-body">
          <h2 style="font-size:30px" class="card-price text-center">{{team.teamName}}<span class="period"></span></h2>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.day}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.startTimeRange}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.lengthOfGame}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.location}}</h5>
          <h5 class="card-title text-muted text-uppercase text-center">{{team.owner.accountName}}</h5>

          <hr>
          <ul class="fa-ul">
            {% for i in team.members.all %}
            <li><span class="fa-li"><i class="fas fa-check"></i></span>{{i.firstName}} {{i.lastName}}</li>
            {% endfor %}
          </ul>
          <form class = "site-form" action="{% url 'joiningTeams' %}" method = "post">
            {% csrf_token %}
            {{form}}
            <input type="hidden" id="orgName" name='orgName' value = "{{orgName}}">
            <input type="hidden" id="teamName" name='teamName' value = "{{team.teamName}}">
            <input type="hidden" id="teamID" name='teamID' value = "{{team.id}}">
            <input type = "submit"  class="btn btn-block btn-primary text-uppercase" value = "Join Team">

          </form>
        </div>
      </div>
    </div>
    {% endfor %}
-->


{% endblock %}

organisation/templates/organisation/viewCompetitions.html
{% extends 'testing.html' %}


{% block table %}
<p> You Are in competitions </p>
<br>

			<form method="get">

				{{filter.form}}

		    <button class="btn btn-primary" type="submit">Search</button>
		  </form>

<br>
<table class="table table-bordered">
    <thead>
      <tr>
        <th>Sport</th>
        <th>Day</th>
				<th>Start Time</th>
				<th>Finish Time</th>
				<th>Start Date</th>
				<th>Final Date</th>
				<th>Gender</th>
				<th>Grade</th>
				<th>Game Length</th>
				<th>Team Advertisements</th>
				<th>Player Advertisements</th>
				{% if org.owner.accountName == request.user.username  %}
				<th> Edit Competition </th>
				<th> Delete Competition </th>
				{% endif %}

      </tr>
    </thead>
    <tbody>
      {% for comp in compList %}
        <tr>
          <td>{{ comp.CompetitionSport}}</td>
					<td>{{ comp.CompetitionDay}}</td>
					<td>{{ comp.CompetitionStartTime}}</td>
					<td>{{ comp.CompetitionEndTime}}</td>
					<td>{{ comp.CompetitionStartDate}}</td>
					<td>{{ comp.CompetitionEndDate}}</td>
					<td>{{ comp.CompetitionGender}}</td>
					<td>{{ comp.CompetitionGrade}}</td>
					<td>{{ comp.LengthOfGame}}</td>
					<td><a href="{% url 'organisation:viewCompetitionTeams' nameOfOrg comp.id %}">View
						<br>
					<a href="{% url 'organisation:addTeamComp' nameOfOrg comp.id %}">Make</td>
						<td><a href="{% url 'organisation:viewCompetitionAdvertisements' nameOfOrg comp.id %}">View
							<br>
						<a href="{% url 'organisation:addAdvertisementComp'  nameOfOrg comp.id %}">Make</td>
					{% if org.owner.accountName == request.user.username  %}
					<td><a href="{% url 'organisation:editCompetition' comp.id %}">Edit</td>
					<td><a href="{% url 'organisation:competitionDelete' comp.id %}">Delete</td>
					{% endif %}

        </tr>
      {% empty %}
        <tr>
          <td colspan="14">No data</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}